# -*- coding: utf-8 -*-
"""Decision Tree Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2ENBrvQO-EBeIP6YoedAKmRogMhj60v

# Decision Tree Regression
"""

#Importing Necessary Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the Dataset
dataset = pd.read_csv('Position_Salaries.csv')

x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

#Training the Decision Tree Regression Model on the Whole Dataset
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x, y)

#Predicting a New Result
regressor.predict([[6.5]])

#Visualising the Decision Tree Regression Results (Higher Resolution)
x_grid = np.arange(min(x), max(x), 0.01)
x_grid = x_grid.reshape((len(x_grid), 1))
plt.scatter(x, y, color = 'red')
plt.plot(x_grid, regressor.predict(x_grid), color = 'blue')
plt.title('Truth or Bluff (Decision Tree Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()